---
- name: Make sure to remove previous added lines
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: "{{ domain }}"
  when: create_hosts_entry
  become: true
  tags:
    - post

- lineinfile:
    dest: /etc/hosts
    line: |
      {{ '127.0.0.1' if inventory_hostname == 'localhost'
        else inventory_hostname }} {{ item.domain }}.{{ domain }}
    state: present
  with_items: "{{ services }}"
  when: item.active and create_hosts_entry
  become: true
  tags:
    - post
