---
version: "2.1"
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
networks:
  default:
    external:
      name: apps
