---
- name: generate docs
  synchronize:
    src: "{{ base_dir }}/mkdocs/{{ item }}"
    dest: "{{ target_dir }}/mkdocs/"
  when: "{{ (services |  selectattr('name', 'search', 'mkdocs') | list | first).active }}"
  with_items:
    - docs
  tags:
    - docs
