version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${STORAGE_PATH}/Movies:/movies
      - ${STORAGE_PATH}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  default:
    external:
      name: apps
