version: "2.1"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - ./config:/config
      - ${STORAGE_PATH}/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  default:
    external:
      name: apps
