# Directories
base_dir: '../../../..'
target_dir: /tmp/mediaserver

# Set to 0 if you want to bind Nginx to ports 80:443
# Systems default is 1024. Reference: https://sysctl-explorer.net/net/ipv4/ip_unprivileged_port_start/
ip_unprivileged_port_start: 1024

# Podman
container_network_name: apps

# Services to deploy
services: 
  - name: bazarr
    active: True
    domain: subtitles
    ports:
      - 6767:6767

  - name: deluge
    active: True
    domain: torrent
    ports:
      - 58846:58846
      - 8112:8112

  - name: flame
    active: True
    domain: home
    ports:
      - 5005:5005

  - name: jackett
    active: True
    domain: tracker
    ports:
      - 9117:9117

  - name: jellyfin
    active: True
    domain: play
    ports:
      - 8096:8096
      - 1900:1900
      - 7359:7359

  - name: nginx
    active: True
    domain: nginx
    ports:
      - 12080:80
      - 12443:443

  - name: ombi
    active: True
    domain: requests
    ports:
      - 3579:3579

  - name: pihole
    active: True
    domain: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8010:80/tcp"
      - "8443:443/tcp"

  - name: planka
    active: True
    domain: tasks
    ports:
      - 1337:1337

  - name: radarr
    active: True
    domain: movies
    ports:
      - 7878:7878

  - name: sonarr
    active: True
    domain: series
    ports:
      - 8989:8989
      
# General
storage_path: /tmp/storage
timezone: America/Sao_Paulo

# Network
domain: domain.local
server_ip: 192.168.0.104
network_cidr: 192.168.77.0/24

# Nginx
use_ssl: False
tls_chain: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
tls_privkey: /etc/letsencrypt/live/{{ domain }}/privkey.pem
tls_trusted_certificate: /etc/letsencrypt/live/{{ domain }}/chain.pem

# Jellyfin
server_url: "play.{{domain}}" # play.domain.local

# Pihole
pihole_domain: hole.pi # TODO fix
password: 'password'
