
version: '3'
services:
  nginx:
          # build: .
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../Certbot-Godaddy/config:/etc/letsencrypt
    restart: unless-stopped

networks:
  default:
    external:
      name: apps
