---
- name: Install podman and podman-compose
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - podman
    - podman-compose
    - aardvark-dns
  tags:
    - always

- name: Create a podman network
  containers.podman.podman_network:
    name: "{{ container_network_name }}"
  tags:
    - always

- name: ensure applications directory is in place
  file:
    path: "{{ target_dir }}/{{ item.name }}"
    state: directory
  when: item.active
  with_items: "{{ services }}"
  tags:
    - nginx
    - prerequisites

- name: Copy podman-compose files to each directory
  template:
    src: "{{ base_dir }}/{{ item.name }}/podman-compose.yml.j2"
    dest: "{{ target_dir }}/{{ item.name }}/podman-compose.yml"
  when: item.active
  with_items: "{{ services }}"
  tags:
    - prerequisites
    - nginx
