version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - "./config:/config"
      - "./cache:/cache"
      - "./css:/jellyfin/jellyfin-web/assets/css"
      - ${STORAGE_PATH}:/media
    restart: "unless-stopped"
    environment:
      - JELLYFIN_PublishedServerUrl=https://play.vcosta.dev
      - UID=1000
      - GID=1000
    ports:
      - 8096:8096
      - 1900:1900
      - 7359:7359
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  default:
    external:
      name: apps
